### ISSUE TITLE
Where downoad?

### ISSUE THREAD

**Issue by c-sanchez** [razar-dev/PowerTube#1]
Hi, I want download PowerTube but I can't,  the only site where looks available is in 4pda and this is an russian website, to make the things worser this requires a captcha in russian, so for me and many people more probably is too much complicated create one account even.
So please, give some apk build here in github or some placemore accesible for everyone.
For now this is the only place where I think I can found something heh.
Regards.

**Comment by razar-dev** [comment]
Hello, sorry that long not respond. 
I uploaded the apk to github.
Last version 4.0.3
https://github.com/razar-dev/PowerTube/raw/master/update/apk/PowerTube_release_4.0.3.apk

Could you write on which English-speaking sites should publish the application?

**Comment by c-sanchez** [comment]
Thank you so much @razar-dev , better later than never heh.
I think you must publish the app in xda developpers forum, is probably the most used english site related with android software.

The forum
https://forum.xda-developers.com/

The section I review often
https://forum.xda-developers.com/android/apps-games

Maybe you found something interesting there :)
