### ISSUE TITLE
BitDefender Antivirus Free for Android Flagging PowerTube as a PUP

### ISSUE THREAD

**Issue by mindwarp42** [razar-dev/PowerTube#6]
I'm running Bitdefender Antivirus Free and PowerTube 4.8.8 on Android 10 (latest Moto G7 stock). BitDefender reports PowerTube as a PUP, classified as Riskware.Downloader.gMMTC. This changed as of January 13, 2020. VirusTotal runs cleanly on the PowerTube .apk. I'm guessing the BitDefender positive is due to PowerTube being (understandably) adware and/or a YouTube downloader. I'll report this to BitDefender as well.

**Comment by razar-dev** [comment]
Thanks for the information about the problem, I just installed Bitdefender and now it does not define the application as PUP.
The false positive may have been related to the app update mechanism.
